name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    # mise can rarely get stuck installing. It normally takes < 10s to install, so this should never be more than a minute
    - uses: jdx/mise-action@v2
      timeout-minutes: 1
      with:
        version: 2024.11.29
    # TODO document: https://github.com/actions/runner-images/issues/4849, https://github.com/actions/runner-images/issues/264
    - uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: zsh libnss3-tools
    # without any additional options, this simply installs the latest version of the cli
    - uses: 1password/load-secrets-action@v2
    - uses: ./.github/actions/direnv-export-and-mask
