# NOTE this file is manually curated, if you change ports, you'll have to update this manually

# random ports are chosen so it doesn't conflict with other projects that are running
# subdomains are used so cookies set on the web domain can be passed to the API domain
# in production, the same domain is used.

# dev server
api.web.localhost: 8200
# test server
api-test.web.localhost: 8201
# javascript server, for development only (not testing)
web.localhost: 8202
# job monitoring
flower.localhost: 8205
