# NOTE this file is manually curated, if you change ports, you'll have to update this manually

# random ports are chosen so it doesn't conflict with other projects that are running

# dev server
api.localhost: 8200
# test server
api-test.localhost: 8201
# javascript server, for development only (not testing)
web.localhost: 8202