# NOTE: for development use only
# ports are not exposed, instead dynamic orb domains are used
services:
  # port 5432
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: development
    ports:
      - ${CI:+5432}:5432
    volumes:
      - app_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 3

  # port 6379
  redis:
    image: redis:latest
    restart: always
    ports:
      - ${CI:+6379}:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 2s
      timeout: 5s
      retries: 3

  # SMTP sinkhole for easily viewing email in development
  # web ui: 8025
  # smtp: 1025
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mailpit_data:
  # NOTE redis data is not persisted, assumed to be ephemeral
  app_postgres_data:
