[project]
name = "python-starter-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "activemodel",
    "alembic>=1.14.0",
    "backoff>=2.2.1",
    "celery-once>=3.0.1",
    "celery[redis]>=5.4.0",
    "clerk-backend-api>=1.3.1",
    "click>=8.1.7",
    "fastapi[standard]>=0.115.3",
    "funcy-pipe>=0.11.1",
    "ipython>=8.28.0",
    "jinja2>=3.1.4",
    "openai>=1.52.2",
    "orjson>=3.10.11",
    "posthog>=3.7.0",
    "psycopg2-binary>=2.9.10",
    "python-decouple-typed>=3.11.0",
    "redis>=5.2.0",
    "sentry-sdk[fastapi]>=2.17.0",
    "sqlalchemy>=2.0.36",
    "sqlmodel>=0.0.22",
    "structlog>=24.4.0",
    "uvicorn>=0.32.0",
]

[project.scripts]
app_name = "app.cli:main"

[tool.uv]
dev-dependencies = [
    "covdefaults>=2.3.0",
    "coverage>=7.6.7",
    "deptry>=0.20.0",
    "ipython>=8.28.0",
    "pretty-traceback>=2024.1021",
    "pyright>=1.1.386",
    "pytest-asyncio>=0.24.0",
    "pytest-celery>=1.1.3",
    "pytest-github-actions-annotate-failures>=0.2.0",
    "pytest>=8.3.3",
    "ruff>=0.7.1",
    "pytest-playwright>=0.5.2",
    "djlint>=1.36.1",
]

[tool.uv.sources]
# https://github.com/astral-sh/uv/issues/9258
# activemodel = { path = "pypi/activemodel" }
activemodel = { git = "https://github.com/iloveitaly/activemodel.git" }
ipython-autoimport = { git = "https://github.com/anntzer/ipython-autoimport.git" }

[tool.pytest.ini_options]
addopts = "--pdbcls=pdbr:RichPdb"

[tool.ruff]
extend-exclude = ["playground"]
force-exclude = true

[tool.ruff.lint]
# to be compatible with vs code ruff plugin
extend-select = ["I"]

# TODO this doesn't play well with the docker image where the coverage comment is running
# [tool.coverage.run]
# plugins = ["covdefaults"]

# If I'm hacking on another package, I like to bundle this within the repository so I can use a single VS Code editor to mutate the files
[tool.pyright]
exclude = [".venv", "pypi", "web/node_modules"]

[dependency-groups]
debugging-extras = [
    "colorama>=0.4.6",
    "datamodel-code-generator>=0.26.3",
    "debugpy>=1.8.8",
    "docrepr>=0.2.0",
    "ipython-autoimport",
    "ipython-ctrlr-fzf>=0.2.1",
    "ipython-suggestions>=1.0.0",
    "ipythonclipboard>=1.0b2",
    "jedi>=0.19.2",
    "pdbr[ipython]>=0.8.9",
    "pretty-traceback>=2024.1021",
    "pyfzf>=0.3.1",
    "sqlparse>=0.5.2",
]
