name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
author: 'Michael Bianco'
branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'composite'
  steps:

    - name: "Install & Run Localias"
      shell: bash
      run: |
        [ ! -d "$HOME/.pki/nssdb" ] && mkdir -p "$HOME/.pki/nssdb" && certutil -d sql:$HOME/.pki/nssdb -N --empty-password

        if ! command -v localias &> /dev/null; then
          cat ${{ github.action_path }}/install.sh | sh -s -- --yes
        fi

        # don't run as daemon so we can see the logs
        sudo localias run &

        # certs are *not* installed by Caddy in the right location by default
        # sudo localias debug cert --print | sudo tee -a /etc/ssl/certs/ca-certificates.crt

        sudo update-ca-certificates

        # https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md
        sudo certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localias-cert -i $(sudo localias debug cert)

        # TODO should we set this here? makes httpie work?
        # REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        # export NODE_EXTRA_CA_CERTS="/path/to/cert.pem"

        # TODO should pick a domain from the environment and test it
        echo "Checking HTTPs via curl..."
        curl --silent --head https://api-test.localhost


