name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
author: 'Michael Bianco'
branding:
  icon: 'box'
  color: 'green'

# https://ray.run/questions/how-do-i-fix-ssl-errors-when-using-playwright-and-google-chrome-to-access-a-site-on-localhost-3000
# https://medium.com/@mudit94/configuring-https-certificates-in-playwright-932ca3fc9f06
# https://superuser.com/questions/1083766/how-do-i-deal-with-neterr-cert-authority-invalid-in-chrome

runs:
  using: 'composite'
  steps:

    - name: "Install & Run Localias"
      shell: bash
      run: |
        set -v

        banner_echo() {
          echo -e "\n\033[0;36m   $1   \033[0m\n"
        }

        # when this directory is properly configured, you should see the following files: cert9.db  key4.db  pkcs11.txt
        # [ ! -d "$HOME/.pki/nssdb" ] && mkdir -p "$HOME/.pki/nssdb" && certutil -d sql:$HOME/.pki/nssdb -N --empty-password

        banner_echo "Checking for NSS DB..."
        # ls -l $HOME/.pki/nssdb

        # sudo update-ca-certificates --fresh

        # banner_echo "Installed certificates:"
        # certutil -L -d sql:${HOME}/.pki/nssdb

        if ! command -v localias &> /dev/null; then
          banner_echo "Installing localias"
          cat ${{ github.action_path }}/install.sh | sh -s -- --yes
        fi

        banner_echo "Starting localias..."
        # don't run as daemon so we can see the logs
        sudo localias run &

        # leave enough time for localias to initialize and generate certificates
        # TODO there's got to be a more deterministic way to handle this
        # sleep 15

        # certs are *not* installed by Caddy in the right location by default
        # specifically, we know this fixes `curl` so it respects our self-signed SSL certificates
        banner_echo "Installing locally signed cert"
        # sudo localias debug cert --print | sudo tee -a /etc/ssl/certs/ca-certificates.crt

        # https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md
        # sudo certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localias-cert -i $(sudo localias debug cert)

        # sudo update-ca-certificates --fresh

        # https://stackoverflow.com/a/75352343/129415
        # TODO should we set this here? makes httpie work?
        # REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
        export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        # export NODE_EXTRA_CA_CERTS="/path/to/cert.pem"

        # TODO should pick a domain from the environment and test it
        banner_echo "Checking HTTPs via curl..."
        curl -vvv --head https://api-test.localhost

        banner_echo "Installed certificates:"
        certutil -L -d sql:${HOME}/.pki/nssdb


