name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
author: 'Michael Bianco'
branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'composite'
  steps:

    - name: "Install & Run Localias"
      shell: bash
      run: |
        if ! command -v localias &> /dev/null; then
          cat ${{ github.action_path }}/install.sh | sh -s -- --yes
        fi

        sudo localias start

        # certs are *not* installed by Caddy in the right location by default
        sudo localias debug cert --print | sudo tee -a /etc/ssl/certs/ca-certificates.crt

        # TODO should we set this here? makes httpie work?
        # REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt


