name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
author: 'Michael Bianco'
branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'composite'
  steps:

    - name: "Install & Run Localias"
      shell: bash
      run: |
        # when this directory is properly configured, you should see the following files: cert9.db  key4.db  pkcs11.txt
        [ ! -d "$HOME/.pki/nssdb" ] && mkdir -p "$HOME/.pki/nssdb" && certutil -d sql:$HOME/.pki/nssdb -N --empty-password

        if ! command -v localias &> /dev/null; then
          cat ${{ github.action_path }}/install.sh | sh -s -- --yes
        fi

        # don't run as daemon so we can see the logs
        sudo localias run &

        # leave enough time for localias to initialize and generate certificates
        # TODO there's got to be a more deterministic way to handle this
        sleep 5

        # certs are *not* installed by Caddy in the right location by default
        # specifically, we know this fixes `curl` so it respects our self-signed SSL certificates
        echo "Installing locally signed cert"
        sudo localias debug cert --print | sudo tee -a /etc/ssl/certs/ca-certificates.crt

        sudo update-ca-certificates --fresh

        # https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md
        sudo certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localias-cert -i $(sudo localias debug cert)
        # sudo certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localias-intermediate-cert -i /root/.local/state/localias/caddy/pki/authorities/local/intermediate.crt

        # https://stackoverflow.com/a/75352343/129415
        # TODO should we set this here? makes httpie work?
        # REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        # export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
        # export NODE_EXTRA_CA_CERTS="/path/to/cert.pem"

        # TODO should pick a domain from the environment and test it
        echo "Checking HTTPs via curl..."
        curl -vvv --head https://api-test.localhost


