name: Build & Publish

on:
  workflow_dispatch:
    # allow ssh access to be enabled via the GH actions UI
    inputs:
      debug_enabled:
        type: boolean
        description: "Run with tmate enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  push:
    branches: [main, master]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  # checkout `just secrets_ci_grant-github-actions`
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  # a important design goal is to avoid custom configuration in CI. This enables tests to be run in a CI-like environment
  # locally, making it easy to replicate CI issues. This is one of the few CI-specific configuration changes since
  # the host where services are located is truly unique to the CI environment.
  DATABASE_HOST: localhost
  REDIS_HOST: localhost

  # https://github.com/Textualize/rich/issues/2769
  COLUMNS: 120

jobs:
  # TODO consider adding a hard timeout for the tail cases
  # timeout-minutes: 20

  app:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        timeout-minutes: 1
      - uses: ./.github/actions/localias
      - run: just up --fast
      - run: just py_setup
      - run: just py_lint
      - run: just db_migrate
      - run: just db_lint
      - run: just py_test

      # NOTE one important problem with `detached` is if something fails, the github environment does seem to get wiped
      # for instance GITHUB_ENV, seems to be cleared out.
      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with: { detached: true }

      # traces and pngs allow us to debug e2e test failures
      - name: Upload test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: ${{ env.PLAYWRIGHT_RESULT_DIRECTORY }}

      # TODO coverage data is not outputting properly right now
      # - name: Add Coverage Comment to PR
      #   id: coverage_comment
      #   uses: py-cov-action/python-coverage-comment-action@v3
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}

  web:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        timeout-minutes: 1
      - run: just js_setup
      - run: just js_lint
      - run: just js_test

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [web, app]
    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        timeout-minutes: 1
      - run: just build
