name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request: {}

# TODO need to understand what is going on here more, make sure we don't need this
#     - name: 🛑 Cancel Previous Runs
#       uses: styfle/cancel-workflow-action@0.11.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  # TODO consider adding a hard timeout for the tail cases
  # timeout-minutes: 10

  web:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      # TODO document: https://github.com/actions/runner-images/issues/4849, https://github.com/actions/runner-images/issues/264
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          # localias requires libnss3-tools for cert generation
          tools: zsh libnss3-tools

      - name: Install localias
        run: cat ./local-alias-install.sh | sh -s -- --yes && sudo localias start
      # without any additional options, this simply installs the latest version of the cli
      - uses: 1password/load-secrets-action@v2
      - run: docker compose up -d
      - run: direnv allow . && direnv export gha >> "$GITHUB_ENV"
      - run: just py_setup
      - run: just py_lint
      - run: just py_test

      # TODO coverage data is not outputting properly right now
      # - name: Add Coverage Comment to PR
      #   id: coverage_comment
      #   uses: py-cov-action/python-coverage-comment-action@v3
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}

  app:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      # TODO document: https://github.com/actions/runner-images/issues/4849, https://github.com/actions/runner-images/issues/264
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: zsh libnss3-tools
      - run: cat ./local-alias-install.sh | sh -s -- --yes && sudo localias start
      # without any additional options, this simply installs the latest version of the cli
      - uses: 1password/load-secrets-action@v2
      - run: direnv allow . && direnv export gha >> "$GITHUB_ENV"
      - run: just js_setup
      - run: just js_lint
      - run: just js_test

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [web, app]
    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: zsh
      - run: direnv allow . && direnv export gha >> "$GITHUB_ENV"
      - run: just build
