name: Build & Deploy

on:
  workflow_dispatch:
    # allow ssh access to be enabled via the GH actions UI
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  push:
    branches: [main, master]
  pull_request: {}

# TODO need to understand what is going on here more, make sure we don't need this
#     - name: 🛑 Cancel Previous Runs
#       uses: styfle/cancel-workflow-action@0.11.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  # TODO consider adding a hard timeout for the tail cases
  # timeout-minutes: 10

  web:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        timeout-minutes: 1
      - uses: ./.github/actions/localias
      - run: just up --fast
      - run: just py_setup
      - run: just py_lint
      - run: just db_migrate
      - run: just db_lint
      # NOTE one important problem with `detached` is if something fails, the github environment does seem to get wiped
      # for instance GITHUB_ENV, seems to be cleared out.
      - uses: mxschmitt/action-tmate@v3
        # if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        # with: { detached: true }
      - run: just py_test

      # TODO coverage data is not outputting properly right now
      # - name: Add Coverage Comment to PR
      #   id: coverage_comment
      #   uses: py-cov-action/python-coverage-comment-action@v3
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}

  app:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        timeout-minutes: 1
      - run: just js_setup
      - run: just js_lint
      - run: just js_test

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [web, app]
    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        timeout-minutes: 1
      - run: just build
