# yml so we can use comments

ignores:
  - eslint
  - typesync
  - "@trivago/prettier-plugin-sort-imports"
  - prettier
  # not an explicit dependency of the client
  # TODO we should upstream a change for this.
  - "@hey-api/client-fetch"
ignorePatterns:
  - bin/*
skipMissing:
  - cypress/*
